# Numpy


In [ ]:
"""
Numpy -- Numeric Python 

-- Numpy supports array which is faster than list and other sequence. 
-- The main datastructure in numpy is ndarray(n-dimension),homogenous,multidimensional array.
-- Numpy array can be created from list tuple or other sequence or by using build in functions.
-- Numpy is essential library for numerical computing in python.


"""

'\nNumpy -- Numeric Python \n\n-- Numpy supports array which is faster than list and other sequence. \n-- The main datastructure in numpy is ndarray(n-dimension),homogenous,multidimensional array.\n-- Numpy array can be created from list tuple or other sequence or by using build in functions.\n-- Numpy is essential library for numerical computing in python.\n\n\n'

In [ ]:
import numpy as np 


In [ ]:
arr = np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [ ]:
arr = np.array((1,2,3,4,5,6))
print(arr)
type(arr)

[1 2 3 4 5 6]


numpy.ndarray

In [ ]:
arr = np.array((1,2,3,4,5,6,"a")) ## Beacause Numpy is Homogeneous 
print(arr)

['1' '2' '3' '4' '5' '6' 'a']


In [ ]:
arr = np.array((1,2,3,4,5,6.6)) ## Beacause Numpy is Homogeneous 
print(arr)

[1.  2.  3.  4.  5.  6.6]


In [ ]:
arr1 = np.array([24])
type(arr1)
arr1.ndim

1

In [ ]:
arr2 = np.array([[10,20,30,40]])
arr2.ndim

2

In [ ]:
arr2 = np.array([[10,20,30,40],[20,30,40,50]])
arr2.ndim

2

In [ ]:
arr3 = np.array([[[1,2,3,4],[1,2,3,4]],[[1,2,3,4],[1,2,3,4]]])
print(arr3)
type(arr3)

[[[1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]]]


numpy.ndarray

# Indexing of Array

In [ ]:
"""
Indexing of Array

"""

'\nIndexing of Array\n\n'

In [ ]:
arr3 = np.array([[[1,2,3,4],[1,2,3,4]],[[8,9,10,11],[12,13,14,15]]])
print(arr3)
print(arr3.ndim)
arr3[0][1][2]

[[[ 1  2  3  4]
  [ 1  2  3  4]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
3


3

In [ ]:
arr3[0,1,2:4] #### ACCESSING THE ELEMENT MORE THAN ONE

array([3, 4])

# Reshape

In [ ]:
arr2 = np.array([[[1,2,3,4,5,6,7,8,9,10,11,12]]])
arr2=arr2.reshape(4,3)
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
"""
Reshape 
12 elements --> 4*3,3*4,12*1,1*12,2*6,6*2
"""

'\nReshape \n12 elements --> 4*3,3*4,12*1,1*12,2*6,6*2\n'

In [ ]:
arr2 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr2=arr2.reshape(2,2,3)
arr2

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
arr2 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

arr2=arr2.reshape(2,2,3)
arr2

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

# ZEROS()

In [ ]:
"""
array = np.zeros(shape,dtype = "float")

"""

'\narray = np.zeros(shape,dtype = "float")\n\n'

In [ ]:
arr3 = np.zeros(9)
arr3

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
arr3 = np.zeros(9,dtype="int")
arr3


array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
arr4 = np.zeros([4,3],dtype="int")
arr4

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
arr5 = np.zeros([2,2,3],dtype="int")
arr5

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

# ONES

In [ ]:
arr6 = np.ones([4,4,8],dtype="int")
arr6.ndim

3

## empty() 

In [ ]:
"""
-- it returns the random values 
"""

'\n-- it returns the random values \n'

In [ ]:
arr = np.empty([4,4,8])
print(arr)

[[[3.61789569e-316 0.00000000e+000 6.93906661e-310 6.93906661e-310
   6.93906661e-310 6.93906661e-310 6.93906661e-310 6.93906661e-310]
  [6.93906661e-310 6.93906661e-310 6.93906661e-310 6.93906661e-310
   6.93906661e-310 6.93906661e-310 6.93906661e-310 6.93906661e-310]
  [6.93906661e-310 6.93906661e-310 6.93906661e-310 6.93906661e-310
   6.93906661e-310 6.93906661e-310 6.93906661e-310 6.93906661e-310]
  [6.93906661e-310 6.93906661e-310 6.93906661e-310 6.93906661e-310
   6.93906661e-310 6.93906661e-310 6.93906661e-310 6.93906661e-310]]

 [[6.93906661e-310 6.93906661e-310 6.93906661e-310 6.93906661e-310
   6.93906661e-310 6.93906661e-310 6.93906661e-310 6.93906661e-310]
  [6.93906661e-310 6.93906661e-310 6.93906661e-310 6.93906661e-310
   6.93906661e-310 6.93906661e-310 6.93906661e-310 6.93906661e-310]
  [6.93906661e-310 6.93906661e-310 6.93906661e-310 6.93906661e-310
   6.93906661e-310 6.93906661e-310 6.93906661e-310 6.93906661e-310]
  [6.93906661e-310 6.93906661e-310 6.93906661e-310 6.

# arange()

In [ ]:
arr6 = np.arange(10,21)
arr6

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr6 = np.arange(10,21,2) ## STEP SIZE
arr6

array([10, 12, 14, 16, 18, 20])

In [ ]:
arr6 = np.arange(31,21,-1).reshape(2,5)
arr6


array([[31, 30, 29, 28, 27],
       [26, 25, 24, 23, 22]])

# EYE()

In [ ]:
"""
It will return
"""

'\nIt will return\n'

In [ ]:
"""
eye(shape , dtype = "float") returns array of zeros with diagonal element 1


"""

'\neye(shape , dtype = "float") returns array of zeros with diagonal element 1\n\n\n'

In [ ]:
arr = np.eye(4,3,dtype = "int")
arr

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

# identity()

In [ ]:
"""
identity() returns the identity matrix


"""

'\nidentity() returns the identity matrix\n\n\n'

In [ ]:
arr = np.identity(7,dtype="int")
arr

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]])

In [ ]:
arr = np.identity(2,dtype="int")
arr

array([[1, 0],
       [0, 1]])

# Random

In [ ]:
"""
## Random
1. rand
2. randint
3. randn


""" 
 

'\n## Random\n1. rand\n2. randint\n3. randn\n\n\n'

# rand

In [ ]:
arr1 = np.random.rand(10)

In [ ]:
arr1

array([0.97101893, 0.08677715, 0.80259619, 0.51793724, 0.52496134,
       0.0885322 , 0.52601706, 0.8077687 , 0.69424676, 0.3112009 ])

# random.randint()

In [ ]:
"""
-- return the random integer between the given range.


"""

'\n-- return the random integer between the given range.\n\n\n'

In [ ]:
arr6 = np.random.randint(10,30,size=5)
arr6

array([27, 22, 28, 15, 15])

# random.randn()

In [ ]:
"""
return the random normally distributed values

"""

'\nreturn the random normally distributed values\n\n'

In [ ]:
arr = np.random.randn(6)
arr

array([-0.97116863,  0.22155874, -0.98173807,  0.79229396,  2.00139042,
        0.8099914 ])

# NUMPY STATISTICS

In [ ]:
import warnings 
warnings.filterwarnings("ignore")

# Mean()

In [ ]:
"""
1. Mean 
Mean is nothing but the average of given set of values

mean = sum of values/ number of Elements

"""

'\n1. Mean \nMean is nothing but the average of given set of values\n\nmean = sum of values/ number of Elements\n\n'

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr
sum(arr)/len(arr)

5.5

In [ ]:
mean = np.mean(arr)
mean 

5.5

In [ ]:
print(f"Mean of {arr} is ",mean)

Mean of [ 1  2  3  4  5  6  7  8  9 10] is  5.5


# Median()

In [ ]:
"""
Median is statistics , is the middle value of the given data when arranged in an order 

"""

'\nMedian is statistics , is the middle value of the given data when arranged in an order \n\n'

In [ ]:
arr = np.array([13,15,14,19,16,12,11,7,19,18,13])
np.sort(arr)

array([ 7, 11, 12, 13, 13, 14, 15, 16, 18, 19, 19])

In [ ]:
np.median(arr)

14.0

# MODE()

In [ ]:
"""
The mode is the value that is repeatedly occuring in a given data.
Most frequent repeated values
"""

'\nThe mode is the value that is repeatedly occuring in a given data.\nMost frequent repeated values\n'

In [ ]:
arr = np.array([13,15,14,19,16,12,11,7,19,18,13,19,15,14,16,13])
arr

array([13, 15, 14, 19, 16, 12, 11,  7, 19, 18, 13, 19, 15, 14, 16, 13])

In [ ]:
from scipy import stats
mode = stats.mode(arr)
mode

ModeResult(mode=array([13]), count=array([3]))

In [ ]:
arr1 = np.array([[2,3,4],[4,6,7],[6,6,7]])
arr1

array([[2, 3, 4],
       [4, 6, 7],
       [6, 6, 7]])

In [ ]:
mode1 = stats.mode(arr1)
mode1

ModeResult(mode=array([[2, 6, 7]]), count=array([[1, 2, 2]]))

# Variance

In [ ]:
"""
Variance : Variance is a measure of how data points differ from the mean.
"""

In [ ]:
arr3 = np.array([1,2,3,4,5,6,7,8,9,10])
var = np.var(arr3)
var

8.25

In [ ]:
np.mean(arr3)

5.5

# Standard Deviation 

In [ ]:
"""
The SD is measure of the amount of variation or dispersion of set of the values

it is a square root of variance

"""

In [ ]:
import statistics as st
arr3 = np.array([1,2,3,4,5,6,7,8,9,10])
sd = st.stdev(arr3)
sd

3.0

In [ ]:
np.std(arr3)

2.8722813232690143

# CEIL()

In [ ]:
"""
Ceil() -- This function returns nearest greater number of the number

"""

In [ ]:
np.ceil(3.0)

3.0

In [ ]:
np.ceil(4.4)

5.0

# Floor()

In [ ]:
"""
It will return the integer part of decimal number

"""

In [ ]:
np.floor(5.8)

5.0

In [ ]:
np.floor(5.9)

5.0

In [ ]:
.5